import { TOOL_ERROR_SCHEMA } from "./redact.mjs";

export function toolDefinitions(aliases, { admin = false, extensions = [], requestedExtensions = [] } = {}) {
  const alias = { type: "string", enum: [...aliases].sort() };
  const nullableString = { type: ["string", "null"] };
  const uuid = { type: "string", format: "uuid" };
  const event = {
    type: "object",
    required: ["seq", "type", "at"],
    properties: {
      seq: { type: "integer", minimum: 1 }, type: { type: "string" }, at: { type: "string", format: "date-time" },
      messageId: uuid, subscriptionId: uuid, responseMessageId: uuid, threadId: uuid, replyTo: { type: ["string", "null"], format: "uuid" },
      alias: { type: "string" }, kind: { type: "string" }, requestHash: { type: "string", pattern: "^[0-9a-f]{64}$" },
      bytesWritten: { type: "integer", minimum: 0 }, errorCode: { type: "string" }, status: { type: "string" }, state: { type: "string" },
      verdict: nullableString, evidence: nullableString, expected: nullableString, observed: nullableString
    },
    additionalProperties: false
  };
  const events = { type: "array", items: event };
  const output = (success) => ({ anyOf: [success, TOOL_ERROR_SCHEMA] });
  const extensionNames = { type: "array", items: { type: "string", enum: ["milestone"] } };
  const exposeExtensionStatus = extensions.length > 0 || requestedExtensions.length > 0;
  const daemonRequired = ["running", "pid", "procStart", "admin", "eventSeq", "targetCount", ...(exposeExtensionStatus ? ["enabledExtensions"] : [])];
  const daemonProperties = { running: { type: "boolean" }, pid: { type: "integer", minimum: 1 }, procStart: { type: "string" }, admin: { type: "boolean" }, eventSeq: { type: "integer", minimum: 0 }, targetCount: { type: "integer", minimum: 0 }, ...(exposeExtensionStatus ? { enabledExtensions: extensionNames, requestedExtensions: extensionNames, extensionMismatch: { type: "boolean" } } : {}) };
  const tools = [
    { name: "peer_targets", description: "List local target aliases and their configured state.", inputSchema: { type: "object", additionalProperties: false }, outputSchema: output({ type: "array", items: { type: "object", required: ["alias", "connected", "permissionMode", "expectedDisplayName", "observedDisplayName"], properties: { alias: { type: "string" }, connected: { type: "boolean" }, permissionMode: { type: "string", enum: ["prompting", "bypass"] }, expectedDisplayName: nullableString, observedDisplayName: nullableString }, additionalProperties: false } }) },
    { name: "peer_status", description: "Verify one allowlisted running Claude Code session without sending.", inputSchema: { type: "object", required: ["alias"], properties: { alias }, additionalProperties: false }, outputSchema: output({ type: "object", required: ["alias", "connected", "sessionId", "cwdMatches", "permission", "observedDisplayName", "pid", "procStart"], properties: { alias: { type: "string" }, connected: { type: "boolean" }, sessionId: uuid, cwdMatches: { type: "boolean" }, permission: { type: "object", required: ["mode", "verifiedBy"], properties: { mode: { type: "string", enum: ["prompting", "bypass"] }, verifiedBy: { type: "string" } }, additionalProperties: false }, observedDisplayName: nullableString, pid: { type: "integer", minimum: 1 }, procStart: { type: "string" } }, additionalProperties: false }) },
    { name: "peer_send", description: "Send one idempotent message. A failure is never retried automatically.", inputSchema: { type: "object", required: ["alias", "messageId", "threadId", "kind", "body"], properties: { alias, messageId: uuid, threadId: uuid, replyTo: { type: ["string", "null"], format: "uuid" }, kind: { type: "string", minLength: 2, maxLength: 64, pattern: "^[a-z][a-z0-9_-]{1,63}$" }, body: { type: "string", minLength: 1, maxLength: 65536 } }, additionalProperties: false }, outputSchema: output({ type: "object", required: ["replay", "messageId", "requestHash", "status"], properties: { replay: { type: "boolean" }, messageId: uuid, threadId: uuid, subscriptionId: uuid, requestHash: { type: "string", pattern: "^[0-9a-f]{64}$" }, alias: { type: "string" }, status: { type: "string", enum: ["requested", "written", "held", "delivered", "idle", "acknowledged", "replied", "terminal", "uncertain_failure", "unknown"] }, events }, additionalProperties: false }) },
    { name: "peer_wait", description: "Wait for a correlated ACK, reply, or idle notice without resending.", inputSchema: { type: "object", required: ["messageId"], properties: { messageId: uuid, require: { type: "string", enum: ["ack", "reply", "idle"] }, timeoutMs: { type: "integer", minimum: 1, maximum: 300000 } }, additionalProperties: false }, outputSchema: output({ type: "object", anyOf: [{ required: ["event", "events"] }, { required: ["timedOut", "messageId", "require", "state", "events"] }], properties: { event, events, evidence: nullableString, timedOut: { type: "boolean" }, messageId: uuid, require: { type: "string" }, state: { type: "string" } }, additionalProperties: false }) },
    { name: "peer_list_events", description: "Read durable local events after a sequence cursor.", inputSchema: { type: "object", properties: { afterSeq: { type: "integer", minimum: 0 }, messageId: { type: ["string", "null"], format: "uuid" } }, additionalProperties: false }, outputSchema: output({ type: "object", required: ["cursor", "events"], properties: { cursor: { type: "integer", minimum: 0 }, events }, additionalProperties: false }) },
    { name: "daemon_status", description: "Read redacted daemon health and event cursor.", inputSchema: { type: "object", additionalProperties: false }, outputSchema: output({ type: "object", required: daemonRequired, properties: daemonProperties, additionalProperties: false }) }
  ];
  if (extensions.includes("milestone")) tools.push(...milestoneTools(output, uuid));
  if (admin) tools.push({ name: "daemon_shutdown", description: "Stop the local daemon. Available only when it was started in admin mode.", inputSchema: { type: "object", additionalProperties: false }, outputSchema: output({ type: "object", required: ["shuttingDown"], properties: { shuttingDown: { type: "boolean" } }, additionalProperties: false }) });
  return tools;
}

function milestoneTools(output, uuid) {
  const hash = { type: "string", pattern: "^[0-9a-f]{64}$" }; const nullableUuid = { type: ["string", "null"], format: "uuid" };
  const milestoneEvent = { type: "object", required: ["seq", "type", "at"], properties: { seq: { type: "integer", minimum: 1 }, type: { type: "string", pattern: "^milestone_" }, at: { type: "string", format: "date-time" }, completionMessageId: uuid, incomingCompletionMessageId: uuid, attemptId: uuid, incomingAttemptId: uuid, milestoneId: { type: "string" }, instructionId: uuid, threadId: uuid, payloadHash: hash, ackMessageId: uuid, ackTransportMessageId: uuid, ackSubscriptionId: uuid, reason: { type: "string" }, status: { type: "string" }, evidence: { type: "string" } }, additionalProperties: false };
  const payload = { type: "object", required: ["instruction_id", "attempt_id", "milestone_id", "files", "tests", "blockers", "last_signal_at"], properties: { instruction_id: uuid, attempt_id: uuid, milestone_id: { type: "string" }, manifest_hash: hash, plan_hash: hash, preview_url: { type: ["string", "null"] }, files: { type: "array", items: { type: "string" } }, tests: { type: "array", items: { type: "object", required: ["command", "scope", "pass", "fail", "skip"], properties: { command: { type: "string" }, scope: { type: "string" }, pass: { type: "integer", minimum: 0 }, fail: { type: "integer", minimum: 0 }, skip: { type: "integer", minimum: 0 } }, additionalProperties: false } }, blockers: { type: "array", items: { type: "object", required: ["code", "message"], properties: { code: { type: "string" }, message: { type: "string" } }, additionalProperties: false } }, last_signal_at: { type: "string", format: "date-time" } }, additionalProperties: false };
  const completion = { type: "object", required: ["completionMessageId", "attemptId", "milestoneId", "instructionId", "threadId", "payloadHash", "payload"], properties: { completionMessageId: uuid, attemptId: uuid, milestoneId: { type: "string" }, instructionId: uuid, threadId: uuid, payloadHash: hash, payload }, additionalProperties: false };
  const ack = { type: ["object", "null"], properties: { messageId: uuid, transportMessageId: nullableUuid, subscriptionId: nullableUuid }, additionalProperties: false };
  const view = { type: "object", required: ["found", "complete", "state", "cursor"], properties: { found: { type: "boolean" }, complete: { type: "boolean" }, state: { type: "string" }, cursor: { type: "integer", minimum: 0 }, completion, ack, lastEvent: milestoneEvent, alreadyDelivered: { type: "boolean" }, alreadyRecovered: { type: "boolean" } }, additionalProperties: false };
  return [
    { name: "milestone_status", description: "Read one durable milestone completion and ACK state.", inputSchema: { type: "object", properties: { completionMessageId: nullableUuid, attemptId: nullableUuid }, additionalProperties: false }, outputSchema: output(view) },
    { name: "milestone_list", description: "List accepted milestone completions after a durable cursor.", inputSchema: { type: "object", properties: { afterSeq: { type: "integer", minimum: 0 }, milestoneId: { type: ["string", "null"] }, attemptId: nullableUuid }, additionalProperties: false }, outputSchema: output({ type: "object", required: ["cursor", "milestones"], properties: { cursor: { type: "integer", minimum: 0 }, milestones: { type: "array", items: view } }, additionalProperties: false }) },
    { name: "milestone_wait", description: "Wait for milestone ledger changes without waking or retrying a peer.", inputSchema: { type: "object", properties: { afterSeq: { type: "integer", minimum: 0 }, completionMessageId: nullableUuid, attemptId: nullableUuid, timeoutMs: { type: "integer", minimum: 1, maximum: 300000 } }, additionalProperties: false }, outputSchema: output({ type: "object", required: ["cursor", "events", "milestone"], properties: { cursor: { type: "integer", minimum: 0 }, events: { type: "array", items: milestoneEvent }, milestone: { anyOf: [view, { type: "null" }] }, timedOut: { type: "boolean" } }, additionalProperties: false }) },
    { name: "milestone_recover_ack", description: "Explicitly open at most one recovery transport for an undelivered milestone ACK.", inputSchema: { type: "object", required: ["completionMessageId", "payloadHash"], properties: { completionMessageId: uuid, payloadHash: hash }, additionalProperties: false }, outputSchema: output(view) }
  ];
}
